services:
  zai-api:
    # # 使用本地构建
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: julienol/zai-api:latest
    container_name: zai-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # 挂载 tokens.txt 文件（如果需要从文件读取 token）
      - ./tokens.txt:/app/tokens.txt:ro
      # 挂载 proxys.txt 文件（如果需要从文件读取代理）
      - ./proxys.txt:/app/proxys.txt:ro
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

